### ISSUE TITLE
除外機能をつける

### ISSUE THREAD

**Issue by guredora403** [actlaboratory/diff_archiver#3]
updaterがパッチに含まれてしまってアップデートができないのでupdaterを除外できるように除外機能が必要です。

**Comment by yncat** [comment]
アップデーターにdiffがなければ含まれないはずですが、どういうことでしょう。

**Comment by guredora403** [comment]
アップデーター無しからアップデーターありのバージョンへアップデートしたようです。それからこれからのアップデーターの変更に備えでbuild.pyでアップデーターをダウンロードして書き込む処理を実装しようと思っているので

**Comment by yncat** [comment]
アップデーターが含まれた段階でbase_versionを更新する想定です

**Comment by yncat** [comment]
> それからこれからのアップデーターの変更に備えでbuild.pyでアップデーターをダウンロードして

どこから？
アップデーターのなにを？バイナリ？ソースコード？

> 書き込む処理を実装

なにを？どこに？なんのために？

**Comment by guredora403** [comment]
updaterリポジトリでリリースをかけて必要ファイルをzipに圧縮したものがダウンロードできるようにしてあるのでそれをbuild.pyでできたパッケージに書き込む処理を実装しようとしています。updaterは共通化されているはずなので。それから将来的にupdaterを更新したときにそれがパッチに含まれているとupdaterがパッチを展開するときに自身を上書きできずにエラーになるので。ていうかいまlampがその状況です。

**Comment by yncat** [comment]
diff_archiverの仕事はdiff_archiveを作ることで、ライブラリとしては、それ以外はしたくないというのがあります。使い方を複雑にしたくないのと、責務を明確にしたいので。
除外したいファイルがある場合は、呼び出し側で対象ファイルをコントロールするようにしてほしいです。diff_archiverにはディレクトリを渡すはずなので、そこに入ってなければ対象にならないはずです。

**Comment by guredora403** [comment]
build.py側で対策します。
